# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [3]:
x = np.zeros(10)
x

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [27]:
x= np.arange(10,49)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

4. Find the shape of previous array in question 3

In [6]:
print(x.shape)

(39,)


5. Print the type of the previous array in question 3

In [8]:
x.dtype

dtype('int64')

6. Print the numpy version and the configuration


In [9]:
print(np.__version__)
print(np.show_config())

1.19.4
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
None


7. Print the dimension of the array in question 3


In [64]:
x= np.arange(10,49)
x.ndim


1

8. Create a boolean array with all the True values

In [42]:
bool_arr = np.ones(10, dtype=bool)
bool_arr

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [47]:
arr=np.arange(0,6).reshape(2,3)
arr

array([[0, 1, 2],
       [3, 4, 5]])

10. Create a three dimensional array



In [54]:
a_3d_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
a_3d_array.shape

(2, 2, 2)

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [55]:
x = np.arange(1,10)
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [56]:
x = np.zeros(10)
x[5]=1
x

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [57]:
array_2D=np.identity(3)
array_2D

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [59]:
arr = np.array([1, 2, 3, 4, 5])
arr.astype(float)

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [67]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
arr3=np.multiply(arr1,arr2)
arr3

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [69]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]]) 
arr2 = np.array([[0., 4., 1.],

            [7., 2., 12.]])
comp = arr1==arr2
comp

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [75]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[a % 2 == 1]


array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [76]:
a[a % 2 == 1]=-1
a

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [98]:
arr = np.arange(10)
c=arr[5:9]=12
c


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

20. Create a 2d array with 1 on the border and 0 inside

In [92]:
x = np.ones((5,5))
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)

1 on the border and 0 inside in the array
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [96]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[arr2d==5]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [109]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
c=arr3d[1]=64
c

64

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [118]:
arr = np.arange(10).reshape(2,5)
arr [ 0, :]

array([0, 1, 2, 3, 4])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [135]:
arr = np.arange(10).reshape(2,5)
arr[0][1]

1

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [146]:
arr = np.arange(10).reshape(2,5)
arr[0:3,1:3]

array([[1, 2],
       [6, 7]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [147]:
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.05535926 0.77423376 0.1629159  0.97019925 0.01078552 0.3696913
  0.81086081 0.97972091 0.70351151 0.43835933]
 [0.43523265 0.54246843 0.80001665 0.65388947 0.42021316 0.1245331
  0.47708453 0.52234074 0.55779568 0.94596646]
 [0.29009826 0.05851681 0.34543555 0.71571548 0.35936887 0.88083404
  0.35862179 0.31418376 0.2775604  0.83688218]
 [0.10530911 0.86037265 0.52082577 0.75803987 0.76075765 0.47246784
  0.03658939 0.88444931 0.33385578 0.33421961]
 [0.81225154 0.36073059 0.18852813 0.94028419 0.5844228  0.81664599
  0.41666487 0.98431161 0.12469884 0.30306543]
 [0.19400142 0.703018   0.16527631 0.87943677 0.04679703 0.3486348
  0.85650962 0.13803899 0.33920798 0.16726516]
 [0.27146625 0.86992528 0.46550283 0.76279711 0.45320927 0.24338056
  0.95603296 0.02227155 0.46000712 0.9320975 ]
 [0.03194804 0.30174499 0.97665355 0.68818316 0.3359944  0.30447632
  0.62545934 0.30689098 0.11039307 0.15357393]
 [0.17566529 0.4623244  0.04344312 0.47740766 0.89685024 0.68966202

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [158]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a , b) 

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [159]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7]),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [167]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names != 'will'] 

array([[-0.24019059, -0.38791858, -2.69233055,  0.19082749],
       [ 0.61608083,  0.09732701,  0.90339569, -0.30584296],
       [ 0.2217614 ,  1.86346475, -0.52418556,  0.55819251],
       [ 0.38000527, -0.13563567, -1.46118777, -0.34179277],
       [-0.3259204 ,  1.93540571,  0.98447444,  0.29192386],
       [ 0.33882736,  0.94300376,  0.95291904,  0.29127518],
       [-0.98999715, -0.465864  , -1.0950828 ,  0.74542487]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [171]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[(names != 'will') & (names != 'joe')]

array([[ 0.49610961, -1.87710989,  0.52747351,  1.94437918],
       [ 0.75054152, -0.64786259, -1.32228441, -0.61166474],
       [-0.76330519,  1.87058699,  1.16854401, -0.19771862],
       [ 0.05889132,  2.0775213 , -1.15289769,  1.74725216],
       [ 2.01771851, -1.55595862, -1.5081352 ,  0.32816075],
       [ 0.64437333,  0.73666747, -0.13934091, -2.06832366],
       [-1.74143097, -1.59322513,  0.94217448,  0.14683137]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [174]:
arr = np.random.rand(1,15).reshape(5,3)
arr

array([[0.64587071, 0.13424656, 0.02514795],
       [0.33614498, 0.96250988, 0.2154561 ],
       [0.18371662, 0.08733781, 0.69864733],
       [0.93294985, 0.29377556, 0.88397612],
       [0.03978683, 0.66255588, 0.04974507]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [175]:
arr = np.random.rand(1,16).reshape(2,2,4)
arr

array([[[0.71147763, 0.31700849, 0.32542878, 0.4474763 ],
        [0.3356227 , 0.97717915, 0.71584254, 0.52538292]],

       [[0.47839505, 0.29797426, 0.0341467 , 0.04637645],
        [0.50375639, 0.61387233, 0.27566821, 0.67639458]]])

33. Swap axes of the array you created in Question 32

In [176]:
arr.swapaxes(0,2)

array([[[0.71147763, 0.47839505],
        [0.3356227 , 0.50375639]],

       [[0.31700849, 0.29797426],
        [0.97717915, 0.61387233]],

       [[0.32542878, 0.0341467 ],
        [0.71584254, 0.27566821]],

       [[0.4474763 , 0.04637645],
        [0.52538292, 0.67639458]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [190]:
arr = np.arange(10)

np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [191]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [192]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b)

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [196]:
print("Printing Original array")
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [197]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [200]:
x = np.random.rand(20)
np.cumsum(x)

array([0.35077224, 0.72837921, 1.02107894, 1.40742271, 1.75248268,
       2.691475  , 3.20581435, 3.4793427 , 3.65432001, 4.40596388,
       5.05992938, 5.71688442, 6.69410372, 6.7361331 , 6.94017215,
       7.65825453, 7.96903948, 8.46095407, 8.81329117, 9.79950881])